[package]
name = "agar-backend"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
rand = { version = "0.5", optional = true }

[features]
default = ["client-side"]
client-side = []
server-side = ["rand"]
